#!/usr/bin/env python

from flask import Flask
from flask import Response
import sqlite3

app = Flask(__name__)
db = "./lounge-radio.sqlite3"

@app.route('/csv')
def list():
	con = sqlite3.connect(db)
	cur = con.cursor()
	
	sql = "SELECT * FROM playlist ORDER BY dt DESC"
	cur.execute(sql)
	
	buffer = "id;unix-tst;title;artist;album\n"
	
	while True:
		row = cur.fetchone()
		if row == None:
			break
		buffer += str(row[0]) + ";\"" + unicode(row[1]) + "\";\"" + \
		          unicode(row[2]) + "\";\"" + unicode(row[3]) + "\";\"" + "\n"
	
	return Response(buffer, mimetype='text/plain')
		
if __name__ == "__main__":
	app.run()
