#!/usr/bin/env python
# -*- coding: UTF-8 -*-

from flask import Flask
from flask import Response
from flask import render_template
import sqlite3
from datetime import datetime
from urllib import quote_plus
from config import *

app = Flask(__name__)

@app.route('/csv')
def csv():
	con = sqlite3.connect(db)
	cur = con.cursor()
	
	sql = "SELECT * FROM playlist ORDER BY dt DESC LIMIT %d" % limit
	cur.execute(sql)
	
	buffer = "id;unix-tst;title;artist;album\n"
	
	while True:
		row = cur.fetchone()
		if row == None:
			break
		buffer += str(row[0]) + ";\"" + unicode(row[1]) + "\";\"" + \
		          unicode(row[2]) + "\";\"" + unicode(row[3]) + "\";\"" + "\n"
	
	return Response(buffer, mimetype='text/plain')
		
@app.route('/')
def playlist():
	con = sqlite3.connect(db)
	cur = con.cursor()
	
	sql = "SELECT * FROM playlist ORDER BY dt DESC LIMIT %d" % 20
	cur.execute(sql)
	
	res = cur.fetchall()
	records = []
	for row in res:
		r = []
		r.append(str(row[0]))
		r.append(quote_plus(row[2].encode('utf8') + " " + row[3].encode('utf8')))
		r.append(str(datetime.fromtimestamp(row[1])))
		r.append(unicode(row[2]))
		r.append(unicode(row[3]))
		r.append(unicode(row[4]))
		records.append(r)
	
	con.close()
	return render_template('playlist.html', records=records)
		
if __name__ == "__main__":
	app.run()
